version: 2
registries:
  npm-registry-registry-npmjs-org:
    type: npm-registry
    url: https://registry.npmjs.org
    token: "${{secrets.NPM_REGISTRY_REGISTRY_NPMJS_ORG_TOKEN}}"
  npm-registry-registry-yarnpkg-com:
    type: npm-registry
    url: https://registry.yarnpkg.com
    token: "${{secrets.NPM_REGISTRY_REGISTRY_YARNPKG_COM_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "19:00"
  labels:
  - dependabot
  versioning-strategy: increase
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@babel/helper-module-transforms"
    versions:
    - 7.12.1
    - 7.13.0
  - dependency-name: "@babel/plugin-transform-exponentiation-operator"
    versions:
    - 7.12.1
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  registries:
  - npm-registry-registry-npmjs-org
  - npm-registry-registry-yarnpkg-com
