!function(e){var r={};function t(n){if(r[n])return r[n].exports;var o=r[n]={i:n,l:!1,exports:{}};return e[n].call(o.exports,o,o.exports,t),o.l=!0,o.exports}t.m=e,t.c=r,t.d=function(e,r,n){t.o(e,r)||Object.defineProperty(e,r,{enumerable:!0,get:n})},t.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},t.t=function(e,r){if(1&r&&(e=t(e)),8&r)return e;if(4&r&&"object"==typeof e&&e&&e.__esModule)return e;var n=Object.create(null);if(t.r(n),Object.defineProperty(n,"default",{enumerable:!0,value:e}),2&r&&"string"!=typeof e)for(var o in e)t.d(n,o,function(r){return e[r]}.bind(null,o));return n},t.n=function(e){var r=e&&e.__esModule?function(){return e.default}:function(){return e};return t.d(r,"a",r),r},t.o=function(e,r){return Object.prototype.hasOwnProperty.call(e,r)},t.p="",t(t.s="./resources/utils/importDocument.js")}({"./resources/utils/importDocument.js":
/*!*******************************************!*\
  !*** ./resources/utils/importDocument.js ***!
  \*******************************************/
/*! exports provided: default */function(e,r,t){"use strict";t.r(r);var n=t(/*! sketch/dom */"sketch/dom"),o=t(/*! ./processLayers */"./resources/utils/processLayers.js");function a(e,r,t){return r in e?Object.defineProperty(e,r,{value:t,enumerable:!0,configurable:!0,writable:!0}):e[r]=t,e}r.default=function(e,r){n.Document.open(r,function(r,t){t.pages.forEach(function(r){"Symbols"!==r.name?r.layers.forEach(function(r){var t=e.selectedPage,c=t.layers[t.layers.length-1],u={x:0,y:0};c&&(u.x=c.frame.x+c.frame.width+80,u.y=c.frame.y);var f=new n.Artboard({parent:e.selectedPage,id:r.id,name:r.name,frame:function(e){for(var r=1;r<arguments.length;r++){var t=null!=arguments[r]?arguments[r]:{},n=Object.keys(t);"function"==typeof Object.getOwnPropertySymbols&&(n=n.concat(Object.getOwnPropertySymbols(t).filter(function(e){return Object.getOwnPropertyDescriptor(t,e).enumerable}))),n.forEach(function(r){a(e,r,t[r])})}return e}({},r.frame,{x:u.x,y:u.y})});Object(o.default)(r.layers,f),e.centerOnLayer(f)}):n.Page.fromNative(r.sketchObject).parent=e})}).close()}},"./resources/utils/processLayers.js":
/*!******************************************!*\
  !*** ./resources/utils/processLayers.js ***!
  \******************************************/
/*! exports provided: default */function(e,r,t){"use strict";t.r(r);var n=t(/*! sketch/dom */"sketch/dom");r.default=function(e,r){return e.map(function(e){if("Group"===e.type){var t=n.Group.fromNative(e.sketchObject);return t.parent=r,t.frame=e.frame,t}if("Text"===e.type){var o=n.Text.fromNative(e.sketchObject);return o.parent=r,o.frame=e.frame,o}if("SymbolInstance"===e.type){var a=n.SymbolInstance.fromNative(e.sketchObject);return a.parent=r,a.frame=e.frame,a}if("Shape"===e.type||"ShapePath"===e.type){var c=n.Shape.fromNative(e.sketchObject);return c.parent=r,c.frame=e.frame,c}if("Image"===e.type){var u=n.Image.fromNative(e.sketchObject);return u.parent=r,u.frame=e.frame,u}console.log("** Unhandled Layer **"),console.log(e)})}},"sketch/dom":
/*!*****************************!*\
  !*** external "sketch/dom" ***!
  \*****************************/
/*! no static exports found */function(e,r){e.exports=require("sketch/dom")}});